[package]
name = "oranda"
description = ">o_o<"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"
exclude = [
  "book/*",
  "src/snapshots/*",
  "src/tests/",
  "tests/",
]

[[bin]]
name = "oranda"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["clap", "tracing-subscriber", "miette/fancy"]

[dependencies]
# Features only used by the cli
clap = { version = "3.2.21", optional = true, features = ["derive"] }
tracing-subscriber = { version = "0.3.15", optional = true }
console = "0.15.1"

# Features used by the cli and library
miette = { version = "5.3.0" }
reqwest = { version = "0.11.11", default-features = false, features = ["gzip", "rustls-tls"] }
thiserror = "1.0.37"
tracing = { version = "0.1.36", features = ["log"] }
lazy_static = "1.4.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = { version = "1.0.85"}
toml = "0.5.9"

comrak = "0.14"
syntect = "5.0"
grass = "0.11.2"

[dev-dependencies]
assert_cmd="2"
assert_fs = "1.0.7"
insta = "1.19.1"
